[package]
name = "chip8-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.21.0"
egui-macroquad = "0.15"
macroquad = { version = "0.3.26", default-features = false }

env_logger = "0.11.5"
log = "0.4.22"
wasm-logger = "0.2.0"
